using System.Buffers.Binary;
using System.Text;
using System.Text.Json;

namespace DfoPacketMcp.Protocol;

internal static class ExtendedNotificationCodec
{
    private static readonly HashSet<string> Supported = new(StringComparer.Ordinal)
    {
        "ACCEPTABLE_QUEST_LIST", "EXPERT_JOB_INFO", "ITEM_EFFECT", "SECRET_SHOP_NPC", "SECRET_SHOP_ITEM_LIST",
        "USER_APC_INFO_TOD", "TOD_CLEAR_REWARD", "TITLE_BOOK_LIST", "TOURNAMENT_INFO", "TOURNAMENT_MAP_INFO",
        "TOURNAMENT_CLEAR_REWARD", "CHARACTER_DEL_BUFF", "CHARACTER_BUFF_DUNGEON", "MINIMAP_ICON_INFO", "DAILY_CHALLENGE",
        "SERVER_BROADCAST", "TAG_CHARACTER_INFO", "RAID_MODIFY",
    };
    public static bool Supports(string name) => Supported.Contains(name);
    public static PacketVariant[] GetManualVariants(string name) => name switch
    {
        "ACCEPTABLE_QUEST_LIST" => [V("quest-id-list", "level:u8 + count:u16 + count*u16 quest ids", "Server/DfoServer/Network/Builders/Init/QuestListBodyBuilder.cs:44")],
        "EXPERT_JOB_INFO" => [V("expert-job-state", "state0:u8 + mode:u8 + mode-specific payload", "Server/DfoServer/Network/Builders/Init/ExpertJobInfoBodyBuilder.cs:31")],
        "ITEM_EFFECT" => [V("exit-ready", "exact length 1", "Server/DfoServer/Network/Builders/Dungeon/BloodAltarPacketBuilder.cs:144")],
        "SECRET_SHOP_NPC" => [V("npc-id", "npcId:i32", "Server/DfoServer/Network/Handlers/SecretShopHandler.cs:42")],
        "SECRET_SHOP_ITEM_LIST" => [V("secret-shop-items", "count:i32 + count*21-byte entries", "Server/DfoServer/Network/Builders/SecretShopItemListBodyBuilder.cs:8")],
        "USER_APC_INFO_TOD" => [V("tower-apc-info", "layer:u8 + dstr name + level/job/grow + dstr guild + guildId + 22 item ids + dstr creature + creatureId", "Server/DfoServer/Network/Builders/Dungeon/TowerOfDespairApcInfoBuilder.cs:36")],
        "TOD_CLEAR_REWARD" => [V("tower-clear-reward", "clearTime:u32 + floor:u16 + count:u8 + count*(itemId:i32 + count:i32)", "Server/DfoServer/Network/Builders/Dungeon/DungeonNotificationBuilder.cs:281")],
        "TITLE_BOOK_LIST" => [V("title-book-category", "infoType:u8 + ownerId:u16 + category:i32 + count:i32 + count*24-byte entries", "Server/DfoServer/Network/Builders/Init/TitleBookListBodyBuilder.cs:29")],
        "TOURNAMENT_INFO" => [V("tournament-info", "dungeonId:i16 + difficulty:u8 + partyLimit:u8 + rounds/actors", "Server/DfoServer/Network/Builders/Dungeon/TournamentPacketBuilder.cs:9")],
        "TOURNAMENT_MAP_INFO" => [V("tournament-map", "x:u8 + y:u8 + seed:u32 + mode:u8 + firstRun:u8 + optional map fields", "Server/DfoServer/Network/Builders/Dungeon/TournamentPacketBuilder.cs:54")],
        "TOURNAMENT_CLEAR_REWARD" => [V("tournament-clear-reward", "round:u8 + exp:u32 + reserved:u8 + two card lists", "Server/DfoServer/Network/Builders/Dungeon/TournamentPacketBuilder.cs:77")],
        "CHARACTER_DEL_BUFF" => [V("character-buff-remove", "count:u8 + count*i32 buff ids", "Server/DfoServer/Network/Builders/Dungeon/SpecialDungeonNotificationBuilder.cs:45")],
        "CHARACTER_BUFF_DUNGEON" => [V("dungeon-buff-state", "count:u16 + count*i32 buff ids", "Server/DfoServer/Network/Builders/Dungeon/SpecialDungeonNotificationBuilder.cs:17")],
        "MINIMAP_ICON_INFO" => [V("minimap-icons", "count:u16 + count*(x:u8 + y:u8 + monsterCode:i32)", "Server/DfoServer/Network/Builders/Dungeon/SpecialDungeonNotificationBuilder.cs:59")],
        "DAILY_CHALLENGE" => [V("daily-challenge-state", "level:u32 + groups + claim flags + tail ids", "Server/DfoServer/Network/Builders/Init/DailyChallengeBodyBuilder.cs:35")],
        "SERVER_BROADCAST" => [V("item-upgrade-notice", "subtype:u8 + success:u8 + userId:u16 + itemId:i32 + level:u8 + optional tail", "Server/DfoServer/Network/Builders/Inventory/ItemUpgradeNoticeBuilder.cs:9"), V("lottery-item-notice", "subtype:u8=2 + mode:u8 + userId:u16 + itemId:i32 + level:u8", "Server/DfoServer/Network/Builders/Lottery/LotteryItemNoticeBuilder.cs:5")],
        "TAG_CHARACTER_INFO" => [V("tag-character-roster", "count:u16 + variable character records", "Server/DfoServer/Network/Builders/Init/StrikerSupportTagCharacterPacketBuilder.cs:102")],
        "RAID_MODIFY" => [V("raid-remove", "raidId:u32 + op:u32=1", "Server/DfoServer/Network/Builders/Raid/RaidPacketBuilder.cs:173"), V("raid-object-update", "raidId:u32 + op:u32=2 + object", "Server/DfoServer/Network/Builders/Raid/RaidPacketBuilder.cs:120"), V("raid-member-update", "raidId:u32 + op:u32=3 + members", "Server/DfoServer/Network/Builders/Raid/RaidPacketBuilder.cs:146"), V("raid-create", "raidId:u32 + op:u32=0 + object + members", "Server/DfoServer/Network/Builders/Raid/RaidPacketBuilder.cs:72")],
        _ => [],
    };
    public static DecodedBody Decode(string name, byte[] body, List<string> d, string? variant) => name switch
    {
        "ACCEPTABLE_QUEST_LIST" => Quest(body,d), "EXPERT_JOB_INFO" => Expert(body,d), "ITEM_EFFECT" => Fixed(body,d,"exit-ready"),
        "SECRET_SHOP_NPC" => Npc(body,d), "SECRET_SHOP_ITEM_LIST" => Shop(body,d), "USER_APC_INFO_TOD" => Apc(body,d),
        "TOD_CLEAR_REWARD" => TodReward(body,d), "TITLE_BOOK_LIST" => Titles(body,d), "TOURNAMENT_INFO" => Tournament(body,d),
        "TOURNAMENT_MAP_INFO" => TournamentMap(body,d), "TOURNAMENT_CLEAR_REWARD" => TournamentReward(body,d),
        "CHARACTER_DEL_BUFF" => Buffs(body,d,false), "CHARACTER_BUFF_DUNGEON" => Buffs(body,d,true), "MINIMAP_ICON_INFO" => Icons(body,d),
        "DAILY_CHALLENGE" => Daily(body,d), "SERVER_BROADCAST" => Broadcast(body,d,variant), "TAG_CHARACTER_INFO" => Tag(body,d),
        "RAID_MODIFY" => RaidModify(body,d), _ => new("unsupported", Base(body)),
    };
    public static byte[] Encode(string name, string? variant, JsonElement f) => name switch
    {
        "ACCEPTABLE_QUEST_LIST" => Build(w=>{w.B(Byte(f,"level")); var a=Arr(f,"questIds");w.U16((ushort)a.Length);foreach(var x in a)w.U16((ushort)x);}),
        "ITEM_EFFECT" => new[]{Byte(f,"value",1)}, "SECRET_SHOP_NPC" => Build(w=>w.I32(I32(f,"npcId"))),
        "CHARACTER_DEL_BUFF" => BuffEncode(f,false), "CHARACTER_BUFF_DUNGEON" => BuffEncode(f,true), "MINIMAP_ICON_INFO" => IconEncode(f),
        "TOD_CLEAR_REWARD" => TodRewardEncode(f), "TOURNAMENT_MAP_INFO" => TournamentMapEncode(f), "SERVER_BROADCAST" => BroadcastEncode(variant,f),
        "RAID_MODIFY" => RaidModifyEncode(variant,f), "EXPERT_JOB_INFO" => ExpertEncode(f), "SECRET_SHOP_ITEM_LIST" => ShopEncode(f),
        "TITLE_BOOK_LIST" => TitlesEncode(f), "DAILY_CHALLENGE" => DailyEncode(f), "TOURNAMENT_CLEAR_REWARD" => TournamentRewardEncode(f),
        _ => [],
    };

    private static DecodedBody Quest(byte[] b,List<string>d){var f=Base(b);var r=new PacketReader(b);if(!r.TryReadByte(out var l)||!r.TryReadUInt16(out var c)){d.Add("quest list header truncated");return new("quest-id-list",f);}f["level"]=l;f["count"]=c;var q=new List<ushort>();for(int i=0;i<c;i++){if(!r.TryReadUInt16(out var x)){d.Add($"quest {i} truncated");break;}q.Add(x);}f["questIds"]=q;Finish(r,f);return new("quest-id-list",f);}
    private static DecodedBody Expert(byte[] b,List<string>d){var f=Base(b);var r=new PacketReader(b);if(!r.TryReadByte(out var s)||!r.TryReadByte(out var m)){d.Add("expert header truncated");return new("expert-job-state",f);}f["state0"]=s;f["mode"]=m; if(m is 1 or 2 or 4){if(!r.TryReadByte(out var c)){d.Add("expert entry count truncated");}else{f["entryCount"]=c;var a=new List<int>();for(int i=0;i<c;i++){if(!r.TryReadInt32(out var x)){d.Add("expert entry truncated");break;}a.Add(x);}f["entries"]=a;if(m==1&&r.TryReadByte(out var qc)){f["qualificationLevels"]=Enumerable.Range(0,qc).Select(_=>r.TryReadByte(out var x)?x:(byte)0).ToArray();r.TryReadInt32(out var el);r.TryReadInt32(out var ee);f["enchanterLevel"]=el;f["enchanterEndurance"]=ee;}}}else if(m==3){r.TryReadInt32(out var g);r.TryReadInt32(out var e);f["disjointMachineGrade"]=g;f["disjointMachineEndurance"]=e;}Finish(r,f);return new("expert-job-state",f);}
    private static DecodedBody Fixed(byte[] b,List<string>d,string v){var f=Base(b);if(b.Length!=1)d.Add($"{v} expects 1 byte");if(b.Length>0)f["value"]=b[0];return new(v,f);}
    private static DecodedBody Npc(byte[] b,List<string>d){var f=Base(b);if(b.Length<4)d.Add("npc id truncated");else f["npcId"]=BinaryPrimitives.ReadInt32LittleEndian(b);return new("npc-id",f);}
    private static DecodedBody Shop(byte[] b,List<string>d){var f=Base(b);var r=new PacketReader(b);if(!r.TryReadInt32(out var c)){d.Add("shop count truncated");return new("secret-shop-items",f);}f["count"]=c;var a=new List<object>();for(int i=0;i<c;i++){if(!r.TryReadInt32(out var id)||!r.TryReadByte(out var flag)||!r.TryReadInt32(out var price)||!r.TryReadInt32(out var rem)||!r.TryReadInt32(out var req)||!r.TryReadInt32(out var cost)||!r.TryReadByte(out var z)){d.Add("shop entry truncated");break;}a.Add(new{itemId=id,rawFlag=flag,price,remainingCount=rem,requiredItemId=req,costValue=cost,reserved=z});}f["entries"]=a;Finish(r,f);return new("secret-shop-items",f);}
    private static DecodedBody Apc(byte[] b,List<string>d){var f=Base(b);var r=new PacketReader(b);if(!r.TryReadByte(out var layer)||!r.TryReadDString(Encoding.UTF8,out var n)){d.Add("APC header truncated");return new("tower-apc-info",f);}f["layer"]=layer;f["name"]=n;r.TryReadByte(out var lv);r.TryReadByte(out var job);r.TryReadByte(out var grow);f["level"]=lv;f["job"]=job;f["growType"]=grow;r.TryReadDString(Encoding.UTF8,out var guild);f["guildName"]=guild;r.TryReadInt32(out var gid);f["guildId"]=gid;var items=new List<int>();for(int i=0;i<22;i++){if(!r.TryReadInt32(out var x))break;items.Add(x);}f["appearanceItemIds"]=items;r.TryReadDString(Encoding.UTF8,out var cr);f["creatureName"]=cr;r.TryReadUInt32(out var ci);f["creatureItemId"]=ci;Finish(r,f);return new("tower-apc-info",f);}
    private static DecodedBody TodReward(byte[] b,List<string>d){var f=Base(b);var r=new PacketReader(b);r.TryReadUInt32(out var t);r.TryReadUInt16(out var floor);r.TryReadByte(out var c);f["clearTimeMilliseconds"]=t;f["floor"]=floor;f["count"]=c;var a=new List<object>();for(int i=0;i<c;i++){r.TryReadInt32(out var id);r.TryReadInt32(out var n);a.Add(new{itemId=id,count=n});}f["rewards"]=a;Finish(r,f);return new("tower-clear-reward",f);}
    private static DecodedBody Titles(byte[] b,List<string>d){var f=Base(b);var r=new PacketReader(b);if(!r.TryReadByte(out var it)||!r.TryReadUInt16(out var o)||!r.TryReadInt32(out var c)||!r.TryReadInt32(out var n)){d.Add("title header truncated");return new("title-book-category",f);}f["infoType"]=it;f["ownerId"]=o;f["category"]=c;f["count"]=n;var a=new List<object>();for(int i=0;i<n;i++){if(!r.TryReadUInt16(out var s)||!r.TryReadInt32(out var id)||!r.TryReadInt32(out var v)||!r.TryReadByte(out var at)||!r.TryReadUInt16(out var du)||!r.TryReadByte(out var sf)||!r.TryReadInt32(out var ei)||!r.TryReadByte(out var eu)||!r.TryReadByte(out var amp)||!r.TryReadUInt16(out var av))break;a.Add(new{slotIndex=s,itemId=id,value=v,attr=at,durability=du,sealFlag=sf,enchantIndex=ei,enchantUpgradeCount=eu,amplifyType=amp,amplifyValue=av});}f["entries"]=a;Finish(r,f);return new("title-book-category",f);}
    private static DecodedBody TournamentMap(byte[] b,List<string>d){var f=Base(b);var r=new PacketReader(b);r.TryReadByte(out var x);r.TryReadByte(out var y);r.TryReadUInt32(out var s);r.TryReadByte(out var mode);r.TryReadByte(out var first);f["x"]=x;f["y"]=y;f["seed"]=s;f["modeFlag"]=mode;f["firstRun"]=first!=0;if(first!=0){r.TryReadUInt16(out var id);f["mapId"]=id;r.TryReadByte(out var a);r.TryReadByte(out var c);r.TryReadByte(out var e);f["reserved"]=new[]{a,c,e};}Finish(r,f);return new("tournament-map",f);}
    private static DecodedBody Tournament(byte[] b,List<string>d){var f=Base(b);var r=new PacketReader(b);r.TryReadInt16(out var id);r.TryReadByte(out var diff);r.TryReadByte(out var lim);f["dungeonId"]=id;f["difficulty"]=diff;f["partyLimit"]=lim;f["rawTailHex"]=Convert.ToHexString(b.AsSpan(r.Offset).ToArray());return new("tournament-info",f);}
    private static DecodedBody TournamentReward(byte[] b,List<string>d){var f=Base(b);var r=new PacketReader(b);r.TryReadByte(out var round);r.TryReadUInt32(out var exp);r.TryReadByte(out var z);f["completedRounds"]=round;f["rewardExperience"]=exp;f["reserved"]=z;var groups=new List<object>();for(int t=0;t<2;t++){r.TryReadByte(out var c);var a=new List<object>();for(int i=0;i<c;i++){r.TryReadInt32(out var id);r.TryReadInt32(out var n);r.TryReadUInt16(out var rz);a.Add(new{itemId=id,amount=n,reserved=rz});}groups.Add(a);}f["cardGroups"]=groups;Finish(r,f);return new("tournament-clear-reward",f);}
    private static DecodedBody Buffs(byte[] b,List<string>d,bool u16){var f=Base(b);var r=new PacketReader(b);if(u16){r.TryReadUInt16(out var c);f["count"]=c;}else{r.TryReadByte(out var c);f["count"]=c;}var a=new List<int>();var n=Convert.ToInt32(f["count"]);for(int i=0;i<n&&r.TryReadInt32(out var x);i++)a.Add(x);f["buffIds"]=a;Finish(r,f);return new(u16?"dungeon-buff-state":"character-buff-remove",f);}
    private static DecodedBody Icons(byte[] b,List<string>d){var f=Base(b);var r=new PacketReader(b);r.TryReadUInt16(out var c);f["count"]=c;var a=new List<object>();for(int i=0;i<c;i++){r.TryReadByte(out var x);r.TryReadByte(out var y);r.TryReadInt32(out var m);a.Add(new{x,y,monsterCode=m});}f["entries"]=a;Finish(r,f);return new("minimap-icons",f);}
    private static DecodedBody Daily(byte[] b,List<string>d){var f=Base(b);var r=new PacketReader(b);r.TryReadUInt32(out var lv);r.TryReadUInt32(out var gc);f["characterLevel"]=lv;f["groupCount"]=gc;var groups=new List<object>();for(int i=0;i<gc;i++){r.TryReadUInt32(out var id);r.TryReadUInt32(out var c);var es=new List<object>();for(int j=0;j<c;j++){r.TryReadUInt32(out var t);r.TryReadUInt32(out var rem);r.TryReadUInt32(out var tar);es.Add(new{trackLikeId=t,remainingValue=rem,targetValue=tar});}groups.Add(new{groupId=id,entries=es});}f["groups"]=groups;r.TryReadUInt32(out var fc);var flags=r.TryReadBytes((int)fc,out var fb)?fb:[];f["claimFlagsHex"]=Convert.ToHexString(flags);r.TryReadUInt32(out var tc);var tails=new List<uint>();for(int i=0;i<tc&&r.TryReadUInt32(out var x);i++)tails.Add(x);f["tailIds"]=tails;Finish(r,f);return new("daily-challenge-state",f);}
    private static DecodedBody Broadcast(byte[] b,List<string>d,string? req){var f=Base(b);var r=new PacketReader(b);r.TryReadByte(out var sub);f["subtype"]=sub;r.TryReadByte(out var mode);f["mode"]=mode;r.TryReadUInt16(out var uid);r.TryReadInt32(out var item);r.TryReadByte(out var lvl);f["userId"]=uid;f["itemId"]=item;f["level"]=lvl;var v=sub==2?"lottery-item-notice":"item-upgrade-notice";if(req!=null&&!req.Equals(v,StringComparison.OrdinalIgnoreCase))d.Add("requested variant does not match subtype");if(r.Remaining>0){r.TryReadBytes(r.Remaining,out var tail);f["tailHex"]=Convert.ToHexString(tail);}return new(v,f);}
    private static DecodedBody Tag(byte[] b,List<string>d){var f=Base(b);var r=new PacketReader(b);r.TryReadUInt16(out var c);f["count"]=c;var a=new List<object>();for(int i=0;i<c;i++){r.TryReadUInt16(out var id);r.TryReadDString(Encoding.UTF8,out var n);r.TryReadByte(out var lv);r.TryReadByte(out var job);r.TryReadByte(out var grow);a.Add(new{characterId=id,name=n,level=lv,job,growType=grow});}f["entries"]=a;Finish(r,f);return new("tag-character-roster",f);}
    private static DecodedBody RaidModify(byte[] b,List<string>d){var f=Base(b);var r=new PacketReader(b);r.TryReadUInt32(out var id);r.TryReadUInt32(out var op);f["raidId"]=id;f["operation"]=op;var v=op switch{1u=>"raid-remove",2u=>"raid-object-update",3u=>"raid-member-update",_=>"raid-create"};if(op==3&&r.TryReadByte(out var c)){f["memberCount"]=c;}else if(op==0&&r.TryReadUInt32(out var inner)){f["objectRaidId"]=inner;f["opaqueTailHex"]=Convert.ToHexString(b.AsSpan(r.Offset).ToArray());}Finish(r,f);return new(v,f);}
    private static byte[] BuffEncode(JsonElement f,bool u16)=>Build(w=>{var a=Arr(f,"buffIds");if(u16)w.U16((ushort)a.Length);else w.B((byte)a.Length);foreach(var x in a)w.I32(x);});
    private static byte[] IconEncode(JsonElement f)=>Build(w=>{var a=Array(f,"entries");w.U16((ushort)a.Length);foreach(var x in a){w.B(Byte(x,"x"));w.B(Byte(x,"y"));w.I32(I32(x,"monsterCode"));}});
    private static byte[] TodRewardEncode(JsonElement f)=>Build(w=>{w.U32(U32(f,"clearTimeMilliseconds"));w.U16((ushort)I32(f,"floor"));var a=Array(f,"rewards");w.B((byte)a.Length);foreach(var x in a){w.I32(I32(x,"itemId"));w.I32(I32(x,"count"));}});
    private static byte[] TournamentMapEncode(JsonElement f)=>Build(w=>{w.B(Byte(f,"x"));w.B(Byte(f,"y"));w.U32(U32(f,"seed"));w.B(Byte(f,"modeFlag"));var first=f.TryGetProperty("firstRun",out var q)&&q.GetBoolean();w.B((byte)(first?1:0));if(first){w.U16((ushort)I32(f,"mapId"));w.B(0);w.B(0);w.B(0);}});
    private static byte[] BroadcastEncode(string? v,JsonElement f)=>Build(w=>{w.B((byte)(v=="lottery-item-notice"?2:1));w.B(Byte(f,"mode",1));w.U16((ushort)I32(f,"userId"));w.I32(I32(f,"itemId"));w.B(Byte(f,"level"));});
    private static byte[] ExpertEncode(JsonElement f)=>Build(w=>{w.B(Byte(f,"state0"));w.B(Byte(f,"mode"));var m=Byte(f,"mode");if(m is 1 or 2 or 4){var a=Array(f,"entries");w.B((byte)a.Length);foreach(var x in a)w.I32(x.GetInt32());if(m==1){var q=Arr(f,"qualificationLevels");w.B((byte)q.Length);foreach(var x in q)w.B((byte)x);w.I32(I32(f,"enchanterLevel"));w.I32(I32(f,"enchanterEndurance"));}}else if(m==3){w.I32(I32(f,"disjointMachineGrade"));w.I32(I32(f,"disjointMachineEndurance"));}});
    private static byte[] ShopEncode(JsonElement f)=>Build(w=>{var a=Array(f,"entries");w.I32(a.Length);foreach(var x in a){w.I32(I32(x,"itemId"));w.B(Byte(x,"rawFlag"));w.I32(I32(x,"price"));w.I32(I32(x,"remainingCount"));w.I32(I32(x,"requiredItemId"));w.I32(I32(x,"costValue"));w.B(0);}});
    private static byte[] TitlesEncode(JsonElement f)=>Build(w=>{w.B(Byte(f,"infoType"));w.U16((ushort)I32(f,"ownerId"));w.I32(I32(f,"category"));var a=Array(f,"entries");w.I32(a.Length);foreach(var x in a){w.U16((ushort)I32(x,"slotIndex"));w.I32(I32(x,"itemId"));w.I32(I32(x,"value"));w.B(Byte(x,"attr"));w.U16((ushort)I32(x,"durability"));w.B(Byte(x,"sealFlag"));w.I32(I32(x,"enchantIndex"));w.B(Byte(x,"enchantUpgradeCount"));w.B(Byte(x,"amplifyType"));w.U16((ushort)I32(x,"amplifyValue"));}});
    private static byte[] DailyEncode(JsonElement f)=>Build(w=>{w.U32(U32(f,"characterLevel",1));var groups=Array(f,"groups");w.U32((uint)groups.Length);foreach(var g in groups){w.U32(U32(g,"groupId"));var e=Array(g,"entries");w.U32((uint)e.Length);foreach(var x in e){w.U32(U32(x,"trackLikeId"));w.U32(U32(x,"remainingValue"));w.U32(U32(x,"targetValue"));}}var flags=PacketInput.ParseHex(f.TryGetProperty("claimFlagsHex",out var h)?h.GetString()??string.Empty:string.Empty);w.U32((uint)flags.Length);foreach(var x in flags)w.B(x);var tails=Array(f,"tailIds");w.U32((uint)tails.Length);foreach(var x in tails)w.U32(x.GetUInt32());});
    private static byte[] TournamentRewardEncode(JsonElement f)=>Build(w=>{w.B(Byte(f,"completedRounds"));w.U32(U32(f,"rewardExperience"));w.B(Byte(f,"reserved"));var groups=Array(f,"cardGroups");for(var t=0;t<2;t++){var g=t<groups.Length&&groups[t].ValueKind==JsonValueKind.Array?groups[t].EnumerateArray().ToArray():[];w.B((byte)g.Length);foreach(var x in g){w.I32(I32(x,"itemId"));w.I32(I32(x,"amount"));w.U16((ushort)I32(x,"reserved"));}}});
    private static byte[] RaidModifyEncode(string? v,JsonElement f)=>Build(w=>{w.U32(U32(f,"raidId"));w.U32(v=="raid-remove"?1u:v=="raid-object-update"?2u:v=="raid-member-update"?3u:0u);});
    private static PacketVariant V(string n,string d,params string[] s)=>new(n,null,s){Discriminator=d,Confidence="confirmed-from-server-source"};
    private static Dictionary<string,object?> Base(byte[] b)=>new(StringComparer.Ordinal){["bodyLength"]=b.Length,["rawHex"]=Convert.ToHexString(b)};
    private static void Finish(PacketReader r,Dictionary<string,object?> f){f["consumedBytes"]=r.Offset;if(r.Remaining>0&&r.TryReadBytes(r.Remaining,out var t))f["trailingHex"]=Convert.ToHexString(t);}
    private static JsonElement[] Array(JsonElement v,string n)=>v.ValueKind==JsonValueKind.Object&&v.TryGetProperty(n,out var p)&&p.ValueKind==JsonValueKind.Array?p.EnumerateArray().ToArray():[];
    private static int[] Arr(JsonElement v,string n)=>Array(v,n).Select(x=>x.GetInt32()).ToArray(); private static byte Byte(JsonElement v,string n,byte d=0)=>v.ValueKind==JsonValueKind.Object&&v.TryGetProperty(n,out var p)?(byte)p.GetInt32():d; private static int I32(JsonElement v,string n,int d=0)=>v.ValueKind==JsonValueKind.Object&&v.TryGetProperty(n,out var p)?p.GetInt32():d; private static uint U32(JsonElement v,string n,uint d=0)=>v.ValueKind==JsonValueKind.Object&&v.TryGetProperty(n,out var p)?p.GetUInt32():d;
    private static byte[] Build(Action<W> a){var w=new W();a(w);return w.ToArray();} private sealed class W{readonly List<byte>b=[];public void B(byte x)=>b.Add(x);public void U16(ushort x){var q=new byte[2];BinaryPrimitives.WriteUInt16LittleEndian(q,x);b.AddRange(q);}public void U32(uint x){var q=new byte[4];BinaryPrimitives.WriteUInt32LittleEndian(q,x);b.AddRange(q);}public void I32(int x){var q=new byte[4];BinaryPrimitives.WriteInt32LittleEndian(q,x);b.AddRange(q);}public byte[] ToArray()=>b.ToArray();}
}



